#title in header
title: "Hao's Blog"

#main info
#owner
owner: "Hi there! I am Hao Liu."
email: haoliutech@gmail.com
info: "A computer science student and software developer based in Adelaide, 🇦🇺."
#description
desc: "I write about tech and my reading. Feel free to contact me."

#menu
menu:
  Resume: /Resume
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: 🌏
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/haoliutech
linkedin: https://www.linkedin.com/in/haoliu3/
twitter: https://twitter.com/HaoLiuTech
youtube: https://www.youtube.com/channel/UCwVLKKtVWIJ2tNB_Y8KUVyQ
#instagram: https://instagram.com/adisaktijrs
stackoverflow: https://stackoverflow.com/users/19679458/hao-liu?tab=profile

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/Hao-Liu-1.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
